package http

import (
	"fmt"
	"log"
	"net/http"

	"github.com/xujiajun/gorouter"
)

// NewServer func returns a new instance of the Server structure
func NewServer(port, version string) *Server {
	mux := gorouter.New()
	return &Server{router: mux, listenPort: port, apiVersion: version}
}

// Server structure
// autoTLSMode enables automatically generation of a new LetsEncrypt certificate.
// customCrtPath and customCrtKeyPath to add a custom TS certificate.
// if autoTLSMode is enabled, custom ceritficates will be ignored.
type Server struct {
	router           *gorouter.Router
	listenPort       string
	apiVersion       string
	autoTLSMode      bool
	customCrtPath    string
	customCrtKeyPath string
}

// ListenAndServe function to handle requests on incoming connections via http
func (s *Server) ListenAndServe() error {
	// Application health check endpoint
	s.router.GET("/health", s.healthCheckHandler)

	// Middlewares
	// TODO: there are middlewares for test. This part should be rewritten
	s.router.NotFoundFunc(notFoundFunc)
	// s.router.Use(withLogging, withTracing, withStatusRecord)

	// Set up API routes with prefix
	api := s.router.Group(s.apiVersion)
	setupRoutes(api)

	// Start web server with autogenerated LetsEncrypt certificates
	if s.autoTLSMode {
		// TODO: implement autogeneration of LetsEncrypt certificates
	}

	// Start web server with custom TLS certificates
	if s.customCrtPath != "" && s.customCrtKeyPath != "" {
		return http.ListenAndServeTLS(s.listenPort, s.customCrtPath, s.customCrtKeyPath, s.router)
	}

	// Start web server
	return http.ListenAndServe(s.listenPort, s.router)
}

// Health check endpoint
func (s *Server) healthCheckHandler(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("OK"))
}

type statusRecorder struct {
	http.ResponseWriter
	status int
}

func (rec *statusRecorder) WriteHeader(code int) {
	rec.status = code
	rec.ResponseWriter.WriteHeader(code)
}

//https://upgear.io/blog/golang-tip-wrapping-http-response-writer-for-middleware/
func withStatusRecord(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		rec := statusRecorder{w, http.StatusOK}
		next.ServeHTTP(&rec, r)
		log.Printf("response status: %v\n", rec.status)
	}
}

func notFoundFunc(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotFound)
	fmt.Fprint(w, "Not found page !")
}

func withLogging(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		log.Printf("Logged connection from %s", r.RemoteAddr)
		next.ServeHTTP(w, r)
	}
}

func withTracing(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		log.Printf("Tracing request for %s", r.RequestURI)
		next.ServeHTTP(w, r)
	}
}
